# Generated by Django 3.2.5 on 2022-11-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
    ]
